security:
    encoders:
        App\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER

    providers:
        administrators:
            entity:
                class: App\Entity\User
                property: username

    firewalls:
        admin_area:
            pattern: ^/
            provider: administrators
            anonymous: ~
            logout:
                path: /logout
                target: /login
            form_login:
                login_path: /login
                check_path: /login_check

                failure_path_parameter: _failure_path

                username_parameter: _username
                password_parameter: _password

                csrf_parameter: _csrf_token
                csrf_token_id: authenticate
                csrf_token_generator: security.csrf.token_manager

                post_only:      true
                remember_me:    false
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }
